## Generate internal data

# drug_look_up
drug_look_up <- data.frame(drug_string = c("bdq",
                                           "dlm", "dld",
                                           "mfx",
                                           "cfz", "clo",
                                           "lfx",
                                           "lzd", "lzn",
                                           "imp"),
                           ideal_drug_name = c("bdq",
                                               rep("dlm", 2),
                                               "mfx",
                                               rep("cfz", 2),
                                               "lfx",
                                               rep("lzd", 2),
                                               "imp"),
                           change_drug_name = c("bdq_change",
                                                rep("dlm_change", 2),
                                                "mfx_change",
                                                rep("cfz_change", 2),
                                                "lfx_change",
                                                rep("lzd_change", 2),
                                                "imp_change"),
                           epi_drug = c("BDQDBDQ", 
                                        rep("DLMDDLM", 2),
                                        "MXDMX", 
                                        rep("CLODCLO", 2), 
                                        "LXDLX", 
                                        rep("LZDDLZD", 2),
                                        "IMPDIMP"),
                           k6_drug = c("Bdq", 
                                        rep("Dld", 2),
                                        "Mfx", 
                                        rep("Cfz", 2), 
                                        "Lfx", 
                                        rep("Lzd", 2),
                                        "ImpCln"),
                           stringsAsFactors = FALSE)

usethis::use_data(drug_look_up, internal = TRUE, overwrite = TRUE)
